### PR TITLE
Add support for arbitrary sidecar containers

### PR DESCRIPTION
**Pull request by arnediekmann**
#### What this PR does / why we need it:

We have the need in a few projects of ours to run a sidecar container to perform nightly backups. This could be used to add a sidecar container for Prometheus like discussed in #10 as well.

#### Checklist

- [x] Chart Version bumped
- [x] e2e tests pass
- [x] Variables are documented in the README.md
- [x] Chart tgz added to /docs and index updated

### CODE REVIEW

**Comment by willholley** [comment]
Thanks @arnediekmann. Can you bump the chart version and run `make publish` to generate the chart package?

It might also be worth adding a test configuration that injects a sidecar, which you can do by adding a new file e.g. `sidecar.yaml` with the complete `values.yaml` that you want to test in https://github.com/apache/couchdb-helm/tree/master/couchdb/ci.

**Comment by arnediekmann** [comment]
Hi @willholley, I'm trying to add a test configuration like you suggested, but kind `0.7.0` doesn't seem to work with `make test` anymore because `kind get kubeconfig-path` was deprecated (https://github.com/kubernetes-sigs/kind/commit/e258374de80352325dd830b8e5faf9270567d1a2). Should I try to fix that in a backwards-compatible manner or is it okay to require kind `>= 0.6.0`?

**Comment by willholley** [comment]
@arnediekmann I submitted a PR at https://github.com/apache/couchdb-helm/pull/24 which updates Kind and Chart Testing. Does that help?

**Comment by arnediekmann** [comment]
@willholley thanks for #24 ... I had to tweak a few things but got it to work eventually as documented in the PR and could add a test set of values.  I also bumped the chart version to 3.2.0 (Assuming this chart is adhering to semver).

**Comment by willholley** [comment]
thanks @arnediekmann - looks good. Can you add the chart binary in the docs dir as well to match?

**Comment by arnediekmann** [comment]
@willholley it's part of of d8a2194. My previous comment was a bit ambiguous :wink:

**Pull request merged**
