### PR TITLE
feat: allow configure persistentVolumeClaimRetentionPolicy

### PR DESCRIPTION
**Pull request by ByJacob**
#### What this PR does / why we need it:

Allow to specify a persistentVolumeClaimRetentionPolicy in both the primary and secondary StatefulSet.

#### Special notes for your reviewer:

This allows for automatic cleanup of PVCs after deletion, etc. An example use case of this is for highly dynamic test environments, where cleaning up the PVCs after deletion of the helm chart is preferred.

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.
- [x] Chart Version bumped
- [x] e2e tests pass
- [x] Variables are documented in the README.md

### CODE REVIEW

**Review by willholley — CHANGES_REQUESTED** [review]
Thanks for the PR! Can you rebase on master? I'm happy to merge this (assuming tests pass), though it's probably worth adding a comment that this is a beta feature in Kubernetes so is generally unavailable. We may have to revisit this if/when this becomes GA.

**Comment by ByJacob** [comment]
> Thanks for the PR! Can you rebase on master? I'm happy to merge this (assuming tests pass), though it's probably worth adding a comment that this is a beta feature in Kubernetes so is generally unavailable. We may have to revisit this if/when this becomes GA.

done

**Review by willholley — CHANGES_REQUESTED** [review]
thanks @ByJacob - can you increment the chart version?

**Comment by ByJacob** [comment]
> thanks @ByJacob - can you increment the chart version?

done :)

**Review by willholley — APPROVED** [review]

**Pull request merged**
