### PR TITLE
Enable splitting view storage and databases

### PR DESCRIPTION
**Pull request by arnediekmann**
#### What this PR does / why we need it:

This PR allows splitting the storage volumes into a view index dir and a data dir for greater performance.

#### Checklist

- [ ] Chart Version bumped
- [ ] e2e tests pass
- [x] Variables are documented in the README.md
- [ ] Chart tgz added to /docs and index updated

### CODE REVIEW

**Comment by willholley** [comment]
Thanks for the PR! I'm actually a bit curious as to whether this is a supported configuration for CouchDB. I recall that Couch assumes view files and primary db files live on the same filesystem, but I could be mistaken. @davisp are you able to clarify?

**Comment by wohali** [comment]
@willholley absolutely not required to be on the same FS that I'm aware. This is definitely something I see in the field often (and, actually recommend, for precisely the same reason as @arnediekmann ...)

Would be very surprised to hear the reverse.

**Comment by willholley** [comment]
Thanks @wohali. I looked back at where we discussed this at Cloudant in relation to running a configuration like this on Kubernetes and using remote storage. The concern was that there's an implied order between writes on secondary indexes and primary so if the storage was spontaneously disconnected, it could happen that we end up with secondary indexes that've synced when the primary data hasn't.

I don't know how well founded the concern is and I don't think it blocks the PR - perhaps just something to keep an eye out for given remote storage tends to be the default option for Kubernetes deployments.

**Comment by wohali** [comment]
We 100% recommend against any sort of remote storage; this was entirely 
2x locally connected drives or RAIDs or zvols.

It sounds like we're in agreement on that :)

**Pull request closed without merging**
