### PR TITLE
Use Chart Testing v3

### PR DESCRIPTION
**Pull request by willholley**
#### What this PR does / why we need it:

Upgrades chart testing to v3 beta 1. This is just to stay current with Kind versions.

#### Which issue this PR fixes

n/a

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.
- [ ] Chart Version bumped
- [ ] e2e tests pass
- [ ] Variables are documented in the README.md
- [ ] Chart tgz added to /docs and index updated

### CODE REVIEW

**Comment by arnediekmann** [comment]
@willholley this PR alone does not work with kind `0.7.0`. I also had to change `kind get kubeconfig-path ...` to `kind get kubeconfig`:

```patch
From 3b9166768457c55f2a8f1334aa0c905a8cf851ce Mon Sep 17 00:00:00 2001
From: Arne Diekmann <arne@neoskop.de>
Date: Mon, 24 Feb 2020 14:15:41 +0100
Subject: [PATCH] Migrate from kubeconfig-path to kubeconfig

---
 test/e2e-kind.sh | 5 +++--
 1 file changed, 3 insertions(+), 2 deletions(-)

diff --git a/test/e2e-kind.sh b/test/e2e-kind.sh
index 36b96ac..efcebd1 100755
--- a/test/e2e-kind.sh
+++ b/test/e2e-kind.sh
@@ -45,9 +45,10 @@ create_kind_cluster() {
     docker_exec mkdir -p /root/.kube
 
     echo 'Copying kubeconfig to container...'
-    local kubeconfig
-    kubeconfig="$(kind get kubeconfig-path --name "$CLUSTER_NAME")"
+    local kubeconfig=$(mktemp)
+    kind get kubeconfig --name "$CLUSTER_NAME" >"$kubeconfig"
     docker cp "$kubeconfig" ct:/root/.kube/config
+    rm "$kubeconfig"
 
     docker_exec kubectl cluster-info
     echo
-- 
2.20.1
```

**Comment by willholley** [comment]
thanks @arnediekmann - updated with your patch

**Comment by arnediekmann** [comment]
I pulled your changes real quick and ran `make test` and can verify that the branch is working with kind `0.7.0` :+1:

**Comment by willholley** [comment]
merged in #26

**Pull request closed without merging**
