### PR TITLE
Require a server instance UUID

### PR DESCRIPTION
**Pull request by arnediekmann**
#### What this PR does / why we need it:

This PR does two things:

- It requires `couchdbConfig.couchdb.uuid` to be set and fails `helm install` otherwise.
- It documents the option and references the documentation

The option is mandatory since replication issues (See apache/couchdb#2298) can occur when all instances have different UUIDs which is what happens when `couchdbConfig.couchdb.uuid` is not set.

#### Which issue this PR fixes

- fixes helm/charts#13481

#### Special notes for your reviewer:

Creating this in favor of #14.

#### Checklist

- [x] Chart Version bumped
- [x] e2e tests pass
- [x] Variables are documented in the README.md
- [x] Chart tgz added to /docs and index updated

### CODE REVIEW

**Comment by willholley** [comment]
@arnediekmann changes look good. Could you bump the chart version [here](https://github.com/apache/couchdb-helm/blob/master/couchdb/Chart.yaml#L3) (I think 3.0.0 would be appropriate given it's a breaking chan ge) and run `make publish` to generate the published chart. The resulting archive and index updates need to be committed so that the chart version is published when this PR is merged.

I think we could also add a note about upgrading from chart version `2.x` to `3.x` [here](https://github.com/apache/couchdb-helm/blob/master/couchdb/README.md#upgrading-an-existing-release-to-a-new-major-version) to make users aware of the new requirement to set the uuid.

**Comment by arnediekmann** [comment]
@willholley Makes sense. I've added the steps needed to upgrade to 3.0.0 and bumped the chart version to that.

**Comment by willholley** [comment]
almost there. `make test` is failing due to `couchdbConfig.couchdb.uuid` not being set. One possibility may be add a file at `couchdb/ci/values.yaml`:

```
couchdbConfig:
   couchdb:
      uuid: "myuniqueid"
```

**Comment by arnediekmann** [comment]
@willholley I just added it. However, I was unable to test it since kind / helm/chart-testing doesn't work reporting:

```
...
ERROR: failed to create cluster: unknown apiVersion:
...
```

With kind version v0.6.0 on go1.13.4. Can you test it in your environment?

**Comment by willholley** [comment]
hmm interesting - I'm using `kind v0.4.0` so perhaps there are breaking changes to address.

**Comment by willholley** [comment]
@arnediekmann it looks like https://github.com/apache/couchdb-helm/blob/master/test/kind-config.yaml needs to be:

```
kind: Cluster
apiVersion: kind.sigs.k8s.io/v1alpha3
nodes:
  - role: control-plane
  - role: worker
```

for kind 0.6.0

**Comment by arnediekmann** [comment]
@willholley I see, that does the trick. Is that backwards compatible, i.e. do you want me to commit that change?

**Comment by arnediekmann** [comment]
@willholley I've just seen that the config file is consistent with [examples of helm/chart-testing][1], so I've committed it. I also ran `make publish` again so the contents (the `ci/required-values.yaml` file) match the repository's code exactly.

[1]: https://github.com/helm/chart-testing/blob/master/examples/kind/test/kind-config.yaml

**Comment by willholley** [comment]
confirmed `make test` passes - thanks @arnediekmann

**Pull request merged**
