### PR TITLE
Fix chart rendering when annotations specified

### LINKED ISSUE #37: setting annotation would fail the installation for chart version above 3.3.0
**Describe the bug**
if settings annotations while installing couchdb using helm, it will fail for versions above 3.3.0.

**Version of Helm and Kubernetes**:
helm version(client/server): "v2.12.3"
k8s version(client/server): "v1.11.0+d4cacc0"

**What happened**:

 it will throw errors as below:

Error: render error in "couchdb/templates/statefulset.yaml": template: couchdb/templates/statefulset.yaml:23:28: executing "couchdb/templates/statefulset.yaml" at <include (print $.Tem...>: error calling include: template: couchdb/templates/_helpers.tpl:14:14: executing "couchdb.fullname" at <.Values.fullnameOver...>: can't evaluate field fullnameOverride in type interface {}

**What you expected to happen**:

It should install couchdb successfully.

**How to reproduce it** (as minimally and precisely as possible):
3.3.1-3.3.2 would fail:
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.3
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.2
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.1

3.3.0 succeed:
helm install --debug --dry-run --set annotations.hello=world,couchdbConfig.couchdb.uuid=xxxxyyy couchdb/couchdb --version 3.3.0

**Anything else we need to know**:

nope.

### LINKED ISSUE #55: The CouchDB Helm chart has an issue
**Describe the bug**
The CouchDB helm chart has an issue with annotations key.
You can find the error in this line: https://github.com/apache/couchdb-helm/blob/main/couchdb/templates/statefulset.yaml#L23

**Version of Helm and Kubernetes**:

**What happened**:
An error occurs if we use the top `annotations` key in a custom values file:
```
  annotations:
    sidecar.istio.io/inject: "false"
```
The error:
```
Error: UPGRADE FAILED: template: smb-cluster/charts/modb/templates/statefulset.yaml:23:28: executing "smb-cluster/charts/modb/templates/statefulset.yaml" at <include (print $.Template.BasePath "/configmap.yaml") .>: error calling include: template: smb-cluster/charts/db/templates/_helpers.tpl:14:14: executing "couchdb.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```
**What you expected to happen**:
We expect it works...

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:
You should replace "." with "$" when you pass the parameter to include func, because you use `with` block before and "." inside this block is not the root context.

So instead of this:
```
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
```
It should be:
```
checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
```

### PR DESCRIPTION
**Pull request by willholley**
#### What this PR does / why we need it:

Commit 70b2777edd3b792c30dd025097ee598b64a45efa caused user-provided
annotations to break the `checksum` StatefulSet annotations. The
`{{ with .Values.annotations }}` instruction changes the scope
under which the checksum is calculated when user annotations are present.

This removes the `{{ with .Values.annotations }}` and instead just
writes out the user-provided annotations directly.

I've also added a user-provided annotation to the `values.yaml` used
in the smoke test to verify the fix.

#### Which issue this PR fixes

  - fixes #37
  - fixed #55

#### Checklist
[Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.
- [x] Chart Version bumped
- [x] e2e tests pass
- [x] Variables are documented in the README.md
- [x] Chart tgz added to /docs and index updated

### CODE REVIEW

**Comment by willholley** [comment]
@kocolosk are you able to review?

**Comment by meringu** [comment]
I just ran into this. :+1: on getting it merged in.

Are you able to fix the merge conflict @willholley?

**Comment by N8th8n8el** [comment]
Status?

**Review by kocolosk — APPROVED** [review]
This looks good, pending a rebase of the chart publishing metadata.

Side comment: I hadn't actually noticed the `checksum/config` automatic update mechanism before. It seems to me that if we're automatically rolling deployments on general config changes we should also do it when `secrets.yaml` changes. In fact I'd think that would be the higher priority one to address.

**Pull request merged**
